<b>Evento Cadastro Usuario</b>
<form action="" class="formActionCadastro">
	Login:<input type="text" class="login"><br/>
	senha:<input type="password" class="Password"><br/>
	email:<input type="text" class="email"><br/>
	<input type="submit" value="Enviar" class="Eventcadastrar"><br/>
</form>

<hr/>
<b>Evento Logar</b>
<form action="" class="formActionLogin">
	Login:<input type="text" class="login"><br/>
	senha:<input type="password" class="Password"><br/>
	<input type="submit" value="Logar" class="Eventlogin"><br/>
</form>
<hr/>


