<!--PAGINA DETALHES DO PEDIDO-->
         <?php 
         $filter = new \NumberFormatter('pt_BR', \NumberFormatter::CURRENCY);
             
         ?>

	<div id="PaginaDoUsuario">
			<div id="MenuDoUsuario">
				<ul class="BoxMenuDoUsuario">
					<li class="BoxMenuInstitucional">
						<a href="" class="MeusDados" title="Meus Dados">Meus Dados</a>
					</li>
					<li class="BoxMenuInstitucional">
						<a href="" class="EndEntrega" title="Endereços de Entregas">Endereços de Entregas</a>
					</li>
					<li class="BoxMenuInstitucional">
						<a href="" class="SeuPedido" title="Seus Pedidos">Seus Pedidos</a>
					</li>
				</ul>
			</div>

		<div id="BoxPaginaDoUsuario" >

			<!-- CONTEUDO DADOS DO USUARIO-->
			<div id="BoxMeusDados" >
				 <div id="MeusDados">
				  <p class="TituloEnderecoResidencial">Meu Cadastro</p>
				   <p class="ttBoxLogin">*Todos os campos são obrigatórios</p><br/>
					<form action="" class="formAction">
					 <label class="FormNome">Nome do Destinatário*:</label><br/><input disabled="disabled" type="text" class="BoxNome" value=""><br/><p class="xxx">(Nome que deverá ser impresso na nota fiscal)</p><br/>
					  <span class="EditarDados" title="Editar Cadastro">Editar</span></a>
					   <input type="submit" title="Salvar Cadastro" value="Salvar Cadastro" class="EventcadastrarEndereco"><br/><br/><br/>
					</form>
				</div>
				
				<div id="MeuEndereco">
				  <p class="TituloEnderecoResidencial">Meu Endereço</br>
                    <span class="DetalheEnderecoResidencial">Para alterar o endereço informe primeiro o CEP</p>
                      <p class="ttBoxLogin">*Todos os campos são obrigatórios</p></br>
						<form action="" class="formAction">
					      <label class="FormCEP">CEP*:</label><br/><input type="text" class="BoxCEP"><br/><br/>
					        <label class="FormEndereco">Endereço*:</label><br/><input type="text" class="BoxEndereco" value=""><br/><p class="xxx">(Deverá ser informado se o endereço é Rua/Avenida/
                                      Quadra/Estrada/Praça e na sequência o nome do endereço)</p><br/>
					           <label class="FormNumero">Numero*:</label>                                      
                               <label class="FormComplemento">Complemento:</label>
                                <br/>
					            <input type="text" class="BoxNumero" >
					            <input type="text" class="BoxComplemento" ><br/><br/>
					            <label class="FormBairro">Bairro*:</label>
					            <label class="FormCidade">Cidade*:</label><br/>
					            <input type="text" class="BoxBairro" >
					            <select class="BoxCidade"><option>Selecione</option></select><br/><br/>
					            <label class="FormEstado">Estado*:</label><br/>
					            <select class="BoxEstado"><option>Selecione</option></select><br/><br/>
					            <label class="FormTelResidencial">Telefone Residencial*:</label><br/><input type="text" class="BoxTelResidencial"><br/><br/>
					            <label class="FormTelCelular">Telefone Celular:</label><br/><input type="text" class="BoxTelCelular"><br/><br/>
					            <label class="FormTelComercial">Telefone Comercial:</label><br/><input type="text" class="BoxTelComercial"><br/><br/>
					            <span class="EditarDados" title="Editar Endereço">Editar</span></a>
					            <input type="submit" title="Salvar Endereço" value="Salvar Endereço" class="EventcadastrarEndereco"><br/><br/><br/>
					        </form>
						
					</div>
					
				</div>

			<!-- FIM DO CONTEUDO DADOS DO USUARIO-->

			<!--ENDEREÇOS DO USUARIO-->
			<div id="BoxMeuEndereco" style="display:none">

				<div id="BoxTitulo">
					<p class="TituloBoxMeuEndereco">Meus Endereços Cadastrados</p>
				    <span class="ButtonNovoEndereco" title="Novo Endereço">Novo Endereço</span></a>
				</div>
					<table id="EditarEndereco">
						<tr class="BoxRadio">
						<th class="radio"><input type="radio" name=myradio value="1" checked></th>
						<th class="TextoEditarEnd"><?=$this->endereco?> - <?=$this->numero?> ,
						<?=$this->bairro?> - <?=$this->cadastro->getMapeamentocidade()->getNome()?> - <?=$this->cadastro->getMapeamentocidade()->getMapeamentoestado()->getNomeclatura()?> - 07111-120</th>

						<th class="bt_excluir"><a href="" title="Excluir endereço de entrega"><img src="<?=$this->basePath()?>/images/bt_excluir.png"></a></th>

						<th class="bt_editar"><a href="" title="Editar endereço de entrega"><img src="<?=$this->basePath()?>/images/icon_editar.png"></a></th>
						</tr>
					</table>

					<table id="EditarEndereco">
						<tr class="BoxRadio">
						<th class="radio"><input type="radio" name=myradio value="1" checked></th>
						<th class="TextoEditarEnd"><?=$this->endereco?> - <?=$this->numero?> ,
						<?=$this->bairro?> - <?=$this->cadastro->getMapeamentocidade()->getNome()?> - <?=$this->cadastro->getMapeamentocidade()->getMapeamentoestado()->getNomeclatura()?> - 07111-120</th>

						<th class="bt_excluir"><a href="" title="Excluir endereço de entrega"><img src="<?=$this->basePath()?>/images/bt_excluir.png"></a></th>

						<th class="bt_editar"><a href="" title="Editar endereço de entrega"><img src="<?=$this->basePath()?>/images/icon_editar.png"></a></th>
						</tr>
					</table>
			</div>

			<!-- FIM DO ENDEREÇOS DO USUARIO-->    



			<!--PEDIDOS-->
				<div id="BoxDetalheDoPedido" style="display:none">
					<?php     
					    foreach($this->recibos AS $recibo)
					    {
					?>
						<ul id="DadosDetalheDoPedido">
							 <li class="tt_Pedidos">Número do pedido</li>
							 <li class="tt_Pedidos">Data do pedido</li>
							 <li class="tt_Pedidos">Forma de pagamento</li>
							 <li class="tt_Pedidos">Valor total</li>
						</ul>

						<ul>
							<li class="DadosDoPedido">
								<div id="ContainerDetalheDoPedido">
								 	<p><a class="txt_NumeroDetalhePedido" href="<?=$this->url("Painel-usuario/Painel-usuario-recibo",array("idPedido" => $recibo->getIdcontrolerecibo()*3500));?>" title="Veja o detalhe do seu pedido">000<?=$recibo->getIdcontrolerecibo()?></a></p>
								</div>
								<div id="ContainerDetalheDoPedido">
								 	<p class="txt_DadosDoPedido"><?
								 	print $recibo->getDtVenda()->format("d/m/Y h:m:s");
						?></p>
								</div>
								<div id="ContainerDetalheDoPedido">
								 	<p class="txt_DadosDoPedido"><?
								 	if($recibo->getFpagamento())
								 	{
								 	    print $recibo->getFpagamento()->getTitulo();
								 	}
								 	else
								 	{
								 		print "Não está definido";
								 	}
								 	?></p>
								</div>
								<div id="ContainerDetalheDoPedido">
								    <p class="txt_ValorDadosDoPedido"><?=$filter->format($recibo->getValor())?></p>
								</div>
							</li>
						</ul>

						<!---->

						<ul id="Status">
							 <li class="tt_Status">Status de pagamento</li>
						</ul>

						<ul>
							<li class="BoxStatus">
							<?php 
							    if(!$recibo->getSpagamento())
							    {
							?>
								<div id="ContainerDetalheDoPedido" class="statusNpedido" rel="<?=$recibo->getIdcontrolerecibo()?>">
								    <a target="_blank" href="https://pagseguro.uol.com.br/v2/checkout/payment.html?code=<?=$recibo->getNpedido()?>" title="Pague Agora"><img class="Txt_PagueAgora" src="<?=$this->basepath()?>/images/PagueAgora.png"></a>
								</div>
								<?php 
							    }else {
                                ?>
                                    <div id="ContainerDetalheDoPedido" class="statusNpedido" rel="<?=$recibo->getIdcontrolerecibo()?>">
    								    <p class="Txt_StatusPagamento"><?=$recibo->getSpagamento()->getTitulo()?></p>
    								</div>
                                <?							    	
							    }
								?>
							</li>
						</ul>

						<!---->

						<ul id="Status">
							 <li class="tt_Status">Status de Envio</li>
						</ul>

						<ul>
							<li class="BoxStatus">
								<div id="ContainerDetalheDoPedido">
								    <p class="Txt_StatusEnvio">
								        <?if(!$recibo->getStatus()) print "Não disponível"; else print $recibo->getStatus();?>
								    </p>
								</div>
							</li>
						</ul>
				
<?php 
					    }	    
?>
				</div>

				<!--FIM DO PEDIDOS-->
	
    		</div>
			  	
	</div>

	