<div class="alert alert-success">
              <strong>Detalhe do pedido</strong> Nessa sessão você entra absolutamente tudo sobre o pedido processado.
            </div>


<style>
/* --------------------------------------------------------------
   TABLES
-------------------------------------------------------------- */

table.form {
	background-color: #fff;
	padding: 0px;
	border: 3px solid #E2E7E9;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    -o-border-radius: 4px;
    border-radius: 4px;
}
table.form td {
	font-size: 12px;
}
table.form td.fieldlabel {
	background-color: #fff;
    text-align: right;
}
table.form td.fieldarea {
	background-color: #efefef;
    text-align: left;
}
table.datatable {
	padding: 0;
	margin: 0;
}
table.datatable th {
	background-color: #1A4D80;
	font-weight: bold;
	text-align: center;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    -o-border-radius: 3px;
    border-radius: 3px;
}
table.datatable td {
	background-color: #FFF;
	border-bottom: 1px solid #EBEBEB;
	font-size: 12px;
}
table.datatable tr.rowhighlight td {
	background-color: #E0E8F3;
}
table.datatable tr:hover td {
	background-color: #EFF2F9;
}
table.datatable th, table.datatable th a, table.datatable th a:visited {
	color: #FFF;
	text-decoration: none;
}
table.datatable th a:hover {
	color: #FFF;
	text-decoration: underline;
}
table.datatable tr:hover td {
	background-color: #F3F3F3;
}
</style>
 <table class="form" width="100%" border="0" cellspacing="2" cellpadding="3">
    <tbody>
      <tr>
        <td class="fieldlabel">Date</td>

        <td class="fieldarea">12/08/2013 11:43</td>

        <td width="15%" class="fieldlabel">Payment Method</td>

        <td class="fieldarea">PayPal</td>
      </tr>

      <tr>
        <td width="15%" class="fieldlabel">Order #</td>

        <td class="fieldarea">4849831192 (ID: 290)</td>

        <td class="fieldlabel">Amount</td>

        <td class="fieldarea">0.00</td>
      </tr>

      <tr>
        <td class="fieldlabel" rowspan="3" valign="top">Client</td>

        <td class="fieldarea" rowspan="3" valign="top"><a href=
        "clientssummary.php?userid=177"></a><a href="clientssummary.php?userid=177">
           Dereck Leme</a> <a href=
        "http://www.dnsstuff.com/tools/freemail/?domain=chientturbo@cwa.mu" target=
        "_blank" title="Check if Free Email Account"><img src="images/info.gif" border=
        "0" align="absmiddle" /></a><br />
        kimds kannwe, qwdqw<br />
        qwd, ,<br />
        Mauritius</td>

        <td class="fieldlabel">Invoice #</td>

        <td class="fieldarea">No Invoice</td>
      </tr>

      <tr>
        <td class="fieldlabel">Status</td>

        <td class="fieldarea"><select id="ajaxchangeorderstatus" style="font-size:14px;">
          <option style="color:#CC8100">
            Pending
          </option>

          <option style="color:#779500" selected="selected">
            Active
          </option>

          <option style="color:#888888">
            Cancelled
          </option>

          <option style="color:#000000">
            Fraud
          </option>

          <option style="color:#3E98C2">
            Under Review
          </option>

          <option style="color:#0ED7F2">
            Wataing Payment
          </option>
        </select>&nbsp;<span id="orderstatusupdated" style=
        "display:none;padding-top:14px;"><img src="images/icons/tick.png" /></span></td>
      </tr>

      <tr>
        <td class="fieldlabel">IP Address</td>

        <td class="fieldarea">196.20.231.206 - <a href=
        "http://www.geoiptool.com/en/?IP=196.20.231.206" target="_blank">Lookup</a> |
        <a href="orders.php?orderip=196.20.231.206">Filter</a> | <a href=
        "configbannedips.php?ip=196.20.231.206&amp;reason=Banned%20due%20to%20Orders&amp;year=2020&amp;month=12&amp;day=31&amp;hour=23&amp;minutes=59&amp;token=99463329c3cb64d2f5f29138584138985da9119e">
        Ban</a></td>
      </tr>

      <tr>
        <td class="fieldlabel">Promotion Code</td>

        <td class="fieldarea">None</td>

        <td class="fieldlabel">Affiliate</td>

        <td class="fieldarea" id="affiliatefield">None - <a href="#" id=
        "showaffassign">Manual Assign</a></td>
      </tr>
    </tbody>
  </table>
  </br>
  <div class="alert alert-info">
         Produtos do pedido:
            </div>
  <table class="table table-condensed">
              <thead>
                <tr>
                  <th width="100">#Id Produto</th>
                  <th>Titulo</th>
                  <th>Valor</th>
                  <th>Quantidade</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
              </tbody>
            </table>