<div class="alert alert-info">
  <h4>Controle financeiro</h4>
      Neste local você entra todas informações necessárias para gerar relatórios e analisar todo tráfego de vendas na sua <b>loja virtual</b>.
</div>


<h5>Ordens de Pagamento</h5>
<div class="btn-group">
  <button class="btn">Ordens Pendentes</button>
  <button class="btn">Pedidos Cancelados</button>
</div>
<br/>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Detalhe</strong> Você pode ver com detalhe quais produtos foram comprados em qualquer pedido processado clicando em cima do <B>N° Pedido</B>.
</div>
<table class="table">
              <thead>
                <tr>
                 <th></th>
                  <th width="50"><center>#ID</center></th>
                  <th><B>N° Pedido</B></th>
                  <th>Data</th>
                  <th>Nome do Cliente</th>
                   <th>Forma de Pagamento</th>
                   <th>Total</th>
                   <th>Situação do pagamento</th>
                    <th width="110">Status</th>
                   
                </tr>
              </thead>
              <tbody>
                <tr class="error">
                <td><input type="checkbox"/></td>
                  <td><center>1</center></td>
                  <td><a href="<?php print $this->url("admin-financeiro/admin-financeiro-action", array("idpedido" => "11010"))?>">4545841</a></td>
                  <td>01/04/2012</td>
                  <td>Dereck Vicentin Leme</td>
                  <td><center>Boleto</center></td>
                  <td>R$10,00</td>
                  <td>Em análise</td>
                  <td>Cancelado</td>
                </tr>
              </tbody>
            </table>
            
            <p><i class="icon-warning-sign"></i> Altere o <b>status</b> do pedido clicando nos botões abaixo, lembre-se que a alteração de status só será possivel apos o sistema identificar o status "Atransação aceita".</p><br/>
            
            <button type="button" class="btn btn-mini btn-primary"">Postado</button>
            <button type="button" class="btn btn-mini btn-info">Em Desenvolvimento</button>
            <button type="button" class="btn btn-mini btn-success">Enviado Para os Correios</button>
            <button type="button" class="btn btn-mini btn-danger">Cancelado</button>