<div class="alert">  
  <strong><h4>Imagem(s) do Produto</h4></strong> <br/> Nessa sessão você sobe e ou recorta as imagens de seus produtos de acordo com as suas necessidades.
</div>

<div class="row">
    <div class="span12">
        <h3>Imagem do Produto</h3>
    </div>
</div>

<hr/>

<div class="row">
    <div class="span12">
       <img id="cropbox" width="<?php echo $this->width;?>" height="<?php echo $this->height;?>" alt="" src="<?php echo $this->basepath()?>/images/produtos/large/<?php echo $this->produto->getFoto();?>">
       
       <form action="<?php echo $this->url('admin-produto-home/admin-default', array('action' => 'crop','id' => $this->produto->getIdproduto()));?>" method="post" onsubmit="return checkCoords();">
           <input type="hidden" name="imagem" value="<?php echo $this->produto->getFoto();?>" >
           <input type="hidden" id="x" name="x" />
		   <input type="hidden" id="y" name="y" />		   
		   <input type="hidden" id="w" name="w" />
		   <input type="hidden" id="h" name="h" />
		   <input type="submit" value="Recortar" class="btn btn-large btn-inverse" />
       </form>
    </div>	
</div>