<?php 
$filter = new \NumberFormatter('pt_BR', \NumberFormatter::CURRENCY);
?>
<!--Pagina Finalizar de Compra-->
<?php 

    if(count($this->carrinhoLista['listaAtual']) >= 1)
    {
?>
		<div id="FinalizarCompra">
				<img class="tt_FinalizarCompra" src="<?=$this->basePath()?>/images/tt_FinalizarCompra.png">
				<div id="BoxFinalizarCompra">

						<ul id="HeaderFinalizarProduto">
							 <li class="FinalizarProduto">Produto</li>
							 <li class="FinalizarQtd">Quantidade</li>
							 <li class="FinalizarValor">Valor Unitário (R$)</li>
							 <li class="FinalizarSub">Subtotal (R$)</li>
							
							 
						</ul>

							<ul id="BoxListaFinalizar">
							
							<!--Produto da lista Finalizar-->
							 <?php 
    foreach($this->carrinhoLista['listaAtual'] AS $produto)
    {
    	?>
								<li class="ListaFinalizar">
								 	<div id="Checkout">
								 		<p class="DescriptionCheckout"><?=$produto['produto']->getTitulo()?></p>
								 	</div>

								 	<div id="Checkout">
								 		<p class="QtdCheckout"><?=$produto['quantidade']?></p>
								 	</div>

								 	<div id="Checkout">
								 		<p class="ValueCheckout"><?=$produto['produto']->getValor(true)?></p>
								 	</div>

								 	<div id="Checkout">
								 		<p class="SubTotalCheckout"><?=$filter->formatCurrency($produto['produto']->getValor()*$produto['quantidade'], 'BRL');?></p>
								 	</div>
								 	
								</li>
								<?php 
    }
								?>
		                        <!--Fim Produto da lista Finalizar-->
							</ul>
				</div>


				<div id="StepsCheckout">

					<div id="BoxLogin">
					<?php 
					    if($this->auth->hasIdentity())
					    {
					?>
					<h5 class="ImgLogin">Login</h5>
							<div id="ContBoxLogin">
								<p class="txtBoxLogin">Bem-vindo(a),<?=$this->auth->getIdentity()->getLogin()?>!<br/><a href="<?php print $this->url("Usuario/UsuarioAction",array("controller"=>"Login","action" => "logout"))?>"><span class="txtBoxLoginSpan" title="sair">Sair</span></a></p>
								<a href="#"><span class="ButtonBoxLogin">voltar para meu carrinho</span></a>
							</div>
							
							
							
							<?php 
					    }
					    else {
                    ?>
                    
                    <!--Conteudo Finalizar Login Vazio-->
                    <div id="BoxLogin">
                    	   <h5 class="ImgLoginOff">Login</h5>
							<div id="ContBoxLogin">
								<p class="ttBoxLogin">*Todos os campos são obrigatórios</p><br/>
								
                                 <div class="return"></div>
									<form action="" class="formAction">

					                  <label class="FormEmail">E-mail*:</label><br/><input type="text" class="BoxEmail actionEmail" value=""><br/><br/>

					                  <label class="FormLogin">Login*:</label><br/><input type="text" class="BoxLogin actionLogin" value=""><br/><p class="xxx">(Criar nome de usuário)</p><br/>

					                  <label class="FormPasswordSenha">Senha*:</label>

                                      <label class="FormPasswordConfirmar">Confirmar senha*:</label><br/>

					                  <input type="password" class="BoxPasswordSenha actionPassoword" >

					                 <input type="password" class="BoxPasswordConfirmar actionPassowordConfirm" ><br/><br/>

					                 <input type="submit" value="criar conta" class="EventcadastrarLoginFinaliza">

					                 <input type="submit" value="login" class="eventOpenPopUp">

					                </form>
								
							</div>
					</div>		
					<!--Fim do Conteudo Finalizar Login Vazio-->


                    <?php 
					    }
							?>
					</div>

					<?php 
					if($this->auth->hasIdentity())
					    {
					?>
					<div id="BoxEndereco">
						

                    		<!--Conteudo Finalizar Endereço Vazio-->
						<div id="BoxEndereco">
								<h5 class="ImgEndereco">Endereço</h5>
							<div id="ContBoxEndereco">
								<p class="ttBoxLogin">*Todos os campos são obrigatórios</p><br/>
                                   <span class="msgCadastrase"></span>
									<form action="" class="formAction">
					                  <label class="FormNome">Nome do Destinatário*:</label><br/><input type="text" class="BoxNome" value=""><br/><p class="xxx">(Nome que deverá ser impresso na nota fiscal)</p><br/>




					                  <label class="FormCEP">CEP*:</label><br/><input type="text" class="BoxCEP" value=""><span class="ajaxMsg" style="color:red;display:none"></span><br/><br/>
					                  

					                  <label class="FormEndereco">Endereço*:</label><br/><input type="text" class="BoxEndereco" value=""><br/><p class="xxx">(Deverá ser informado se o endereço é Rua/Avenida/
Quadra/Estrada/Praça e na sequência o nome do endereço)</p><br/>

					                  <label class="FormNumero">Numero*:</label>   <br/>
					                  <input type="text" class="BoxNumero" value=""><Br/><br/>

					                 
					                  <label class="FormBairro">Bairro*:</label>
					                  <label class="FormCidade">Cidade*:</label><br/>

					                  <input type="text"  class="BoxBairro" value="">
					                   <select class="BoxCidade" disabled="disabled"><option  >Selecione</option></select><br/><br/>
					                  <label class="FormEstado">Estado*:</label><br/>
					                  <select class="BoxEstado">
					                  <option>Selecione</option>
					                      <?php 
					                          foreach($this->estados AS $estados)
					                          {
					                      ?>
					                      <option><?=$estados->getNome()?></option>
					                      <?php 
					                          }?>
					                  </select><br/><br/>




					                 <input type="submit" value="Salvar Endereço" class="EventcadastrarEndereco"><br/><br/><br/>

					                </form>
							</div>
						</div>		
							<!--Fim do Conteudo Finalizar Endereço Vazio-->
							
					</div>
<?php 
					    }
					    else
					    {
					    	?>
					    	<div id="BoxEndereco">
						

                    		<!--Conteudo Finalizar Endereço Vazio-->
						<div id="BoxEndereco">
								<h5 class="ImgEnderecoOff">Endereço</h5>
							<div id="ContBoxEndereco">
								<p class="ttBoxLogin">*Todos os campos são obrigatórios</p><br/>
                                   
									<form action="" class="formAction">

					                  <label class="FormNome">Nome do Destinatário*:</label><br/><input disabled="disabled" type="text" class="BoxNome" value=""><br/><p class="xxx">(Nome que deverá ser impresso na nota fiscal)</p><br/>




					                  <label class="FormCEP">CEP*:</label><br/><input disabled="disabled" type="text" class="BoxCEP"><br/><br/>
					                  

					                  <label class="FormEndereco">Endereço*:</label><br/><input  disabled="disabled" type="text" class="BoxEndereco" value=""><br/><p class="xxx">(Deverá ser informado se o endereço é Rua/Avenida/
Quadra/Estrada/Praça e na sequência o nome do endereço)</p><br/>

					                  <label class="FormNumero">Numero*:</label>                                      
                                      <label class="FormComplemento">Complemento:</label>

                                      <br/>
					                  <input type="text"  disabled="disabled" class="BoxNumero" >
					                  <input type="text"  disabled="disabled" class="BoxComplemento" ><br/><br/>

					                  <label class="FormBairro">Bairro*:</label>
					                  <label class="FormCidade">Cidade*:</label><br/>

					                  <input type="text" disabled="disabled" class="BoxBairro" >
					                   <select class="BoxCidade" disabled="disabled"><option>Selecione</option></select><br/><br/>
					                  <label class="FormEstado">Estado*:</label><br/>
					                  <select class="BoxEstado" disabled="disabled"><option>Selecione</option></select><br/><br/>




					                 <input type="submit" value="Salvar Endereço" class="EventcadastrarEnderecoOff"><br/><br/><br/>

					                </form>
							</div>
						</div>		
							<!--Fim do Conteudo Finalizar Endereço Vazio-->
							
					</div>
					    	<?php 
					    }
?>
					<div id="BoxPagamento">
						<?php 
					    if($this->auth->hasIdentity())
					    {
					?>
						<h5 class="ImgPagamentoOff">Pagamento</h5>
							<div id="ContBoxPagamento">
							<span class="obs_pagamento">Conclua seu cadastro com cep para calcular o frente.</span>
									<p class="txtResumo">Resumo da compra</p>
									<p class="txtBoxResumo">Valor total dos produtos:</p> 
								    <span class="txtBoxResumoValor"><?=$this->carrinhoLista['valorTotal']?></span>
								    <p class="txtBoxResumo">Despesas com frete:</p> 
								    <span class="txtBoxResumoValor">Indisponível</span>
								    <p class="txtBoxResumo">Valor total a pagar:</p> 
								    <span class="txtBoxResumoValor">R$ 10,00</span>
									<img class="BoxResumoPagSeguro" src="<?=$this->basePath()?>/images/pagseguro.png">
									<p class="txtPagSeguro">PagSeguro é a solução completa para pagamentos online, que garante a segurança de quem compra na web. Quem compra com PagSeguro tem a garantia de produto ou serviço entregue ou seu dinheiro de volta.</p>
								<a href="#"><span class="BoxPagamentoButtonOff">Finalizar pagamento</span></a>
							</div>
							<?php 
					    }
					    else {
					    	
                    ?>

                    <!--Conteudo Finalizar Pagamento Vazio-->
						<div id="BoxPagamento">
						   <h5 class="ImgPagamentoOff">Pagamento</h5>
							<div id="ContBoxPagamento">
							<span class="obs_pagamento">É necessário estar logado para calcular o frete e finalizar o pagamento.</span>
									<p class="txtResumo">Resumo da compra</p>
									<p class="txtBoxResumo">Valor total dos produtos:</p> 
								    <span class="txtBoxResumoValor"><?=$this->carrinhoLista['valorTotal']?></span>
								    <p class="txtBoxResumo">Despesas com frete:</p> 
								    <span class="txtBoxResumoValor">Indisponível</span>
								    <p class="txtBoxResumo">Valor total a pagar:</p> 
								    <span class="txtBoxResumoValor">R$ 00,00</span>
									<img class="BoxResumoPagSeguro" src="<?=$this->basePath()?>/images/pagseguro.png">
									<p class="txtPagSeguro">PagSeguro é a solução completa para pagamentos online, que garante a segurança de quem compra na web. Quem compra com PagSeguro tem a garantia de produto ou serviço entregue ou seu dinheiro de volta.</p>
								<a href="#"><span class="BoxPagamentoButtonOff">Finalizar pagamento</span></a>
							</div>
						</div>
					<!--Fim da Conteudo Pagamento Vazio-->		
							<?php 
					    }
							?>
					</div>

				</div>		
				
		</div>
          <!--Fim da Pagina Finalizar Compra-->
          <?php 
    }
    else {
    	 
    	?>			           <!--Pagina Vazia do Carrinho de Compras-->
           <div id="CestaCompras">
    				<img class="tt_CestaCompras" src="<?=$this->basePath()?>/images/tt_CestaCompras.png">
    					<div id="BoxCestaCompras">
    
    						<img class="imgCestaVazia" src="<?=$this->basePath()?>/images/cestaVazia.png" title="cesta vazia">
    
    							<div id="CestaVazia">
    								<p class="txtCestaVazia"><span class="ttCestaVazia">Sua cesta de compras esta vazia.</span><br/><br/>
    								Você ainda não adicionou nenhum produto ao seu carrinho de compras. Navegue pelo site<br/> e selecione os produtos desejados.</p>
    								<a href="#"><span class="ButtonCestaVazia" title="continuar comprando">CONTINUAR COMPRANDO</span></a>
    							</div>	
    
    					</div>
    		</div>
    		                <!--Fim da Pagina Vazia do Carrinho de Compras-->		
    <?php 
        }
    ?>	