<?php 
$filter = new \NumberFormatter('pt_BR', \NumberFormatter::CURRENCY);
?>
<!--Slider de Produtos-->
	<div id="SliderProdutosGeral">
		<img class="tt_SliderProdutos" src="<?=$this->basePath()?>/images/tt_SliderProdutos.png">
			<div id="StructureSlider">	
			 <a href=""><span class="seta_slider_esquerda"><img src="<?=$this->basePath()?>/images/seta_slider_esquerda.png"></span></a>
				<div id="BoxSliderProdutos">
					<ul id="BaseSlider">
						<li class="ContSlider">
							<a href=""><img class="ImgContSlider" src="<?=$this->basePath()?>/images/img_slide.png"></a>
						</li>
					</ul>
				</div>
			 <a href=""><span class="seta_slider_direita"><img src="<?=$this->basePath()?>/images/seta_slider_direita.png"></span></a>
			
				  <div id="ProductDescription" style="display:none">
				  	
				  	<!--Descrição dos Produtos do Slider-->
				 	  <div id="BoxProductDescription">
				 	  	<img class="detalhe_slider" src="<?=$this->basePath()?>/images/detalhe_slider.png">
				 	  	<div id="ProductDescriptionContent">
				 	  		<p class="txtProductDescription">Lorem ipsum </p>
				 	  		<p class="ValueProductDescription">R$ 00,00</p>
				 	  		<a href=""><span class="ButtonProductDescription">Adicionar na cesta</span></a>
				 	  	</div> 
				 	  </div>
				 	  <!--Fim Descrição dos Produtos do Slider-->

				  </div>

			</div> 
	</div>
      <!--Fim do Slider de Produtos-->
<?php 
    if(count($this->carrinhoLista['listaAtual']) >= 1)
    {
?>

         <!--Pagina do Carrinho de Compras-->
		<div id="CestaCompras">
				<img class="tt_CestaCompras" src="<?=$this->basePath()?>/images/tt_CestaCompras.png">
				<div id="BoxCestaCompras">

						<ul id="HeaderCestaCompras">
							 <li class="CestaTopoProduto">Produto</li>
							 <li class="CestaTopoDescricao">Descrição</li>
							 <li class="CestaTopoValor">Valor R$</li>
							 <li class="CestaTopoQtd">Quantidade</li>
							 <li class="CestaTopoSub">Subtotal R$</li>
							 <li class="CestaTopoExcluir">Excluir</li>
						</ul>

							<ul id="BoxListaProduto">
							
            <?php 
    foreach($this->carrinhoLista['listaAtual'] AS $produto)
    {
    	?>
    	
								 <li class="ListaDaCesta">
								     
								 	<div id="ProductsFromBasket">
								 		<img class="ImgProductsBasket" src="<?=$this->basePath()?>/images/img_pagina_carrinho_de_compra.png">
								 	</div>
								 	<div id="ProductsFromBasket">
								 		<p class="DescriptionProductsBasket"><?=$produto['produto']->getTitulo()?></p>
								 	</div>
								 	<div id="ProductsFromBasket">
								 		<p class="ValueProductsFromBasket"><?=$produto['produto']->getValor(true)?></p>
								 	</div>
                                    <input class="actionCode" type="hidden" value="<?=$produto['produto']->getIdproduto()?>"/>
								 	<div id="ProductsFromBasket">
									 	<span class="AmountProductsFromBasket">	
			            				  <input class="qtd_carrinho" type="text" name="quantidade" value="<?=$produto['quantidade']?>">
			            					<ul class="Qtd_Mudar">
			            					  <li class="change_qtd_carrinho MoreItens"> <a href="#">mais</a></li>
			                                   <li class="change_qtd_carrinho  LessItens"> <a href="#">menos</a></li>
			            					</ul>
			            				</span>
								 	</div>

								 	<div id="ProductsFromBasket">
								 		<p class="SubTotalProductsFromBasket"><?=$filter->formatCurrency($produto['produto']->getValor()*$produto['quantidade'], 'BRL');?></p>
								 	</div>

								 	<div id="ProductsFromBasket">
								 	  <a href="">
								 		<img class="CloseProductsFromBasket" src="<?=$this->basePath()?>/images/fechar_carrinhodecompras.png" title="excluir do carrinho de compras">
								 	  </a>
								 	</div>
								  </li>
							  
								<!--Fim do Produto no Carrinho-->
							</ul>

						<ul id="HeaderCestaCompras">
							  <li class="txt_prazoDentrega">Consulte o valor do seu frete</li>
								 <li class="SeuCep">
								 	<p class="txt_SeuCep">Digite seu CEP</p>

								 	    <a href="#" title="calcular frete">
									 		<span class="CalcFret">
									 		 Calcular frete
									 		</span>
									 		<input value="00000" class="DigCep1">
									 		<input value="000" class="DigCep2">
									 	</a>
								 </li>

								 <li>
								 	<a class="ProcurarCep" href="#" title="encontre seu cep">
								 		<u>Não sei meu CEP</u>
								 	</a>
								 </li>
						</ul>

						<ul id="BoxListaProduto">
						 <span class="BoxEntrega">
						 	<img class="ImgBoxEntrega" src="<?=$this->basePath()?>/images/entrega_Cesta.png">
						 	 <p class="TxtBoxEntrega">
						 		<span class="CaixaAltaEntrega">prazo máximo de entrega:</span>
						 		 até 7 dias úteis</p>
						 </span>
							<li class="ListaDaCesta">
								<img class="AvisoCarrinho" src="<?=$this->basePath()?>/images/aviso_carrinho.png">
								<p class="txt_aviso"><span class="txt_aviso_atencao">Atenção:</span> O prazo começa a contar a partir da aprovação do crédito.</p>
		                        <p class="txt_frete">FRETE: GRÁTIS</p>
		                        <p class="txt_TotalFrete">TOTAL COM FRETE:</p>
		                        <p class="CalcSomaValor"><?=$this->carrinhoLista['valorTotal']?></p>
							</li>

						  <a href="#"><span class="ButtonCarCompras_Comprar">CONTINUAR COMPRANDO</span></a>
						  <a href="#"><span class="ButtonCarCompras_Finalizar">FINALIZAR COMPRA</span></a>

						</ul>

				</div>		
				
		</div>
		<?php 
        }
    }
    else {
    	
?>			           <!--Pagina Vazia do Carrinho de Compras-->
       <div id="CestaCompras">
				<img class="tt_CestaCompras" src="<?=$this->basePath()?>/images/tt_CestaCompras.png">
					<div id="BoxCestaCompras">

						<img class="imgCestaVazia" src="<?=$this->basePath()?>/images/cestaVazia.png" title="cesta vazia">

							<div id="CestaVazia">
								<p class="txtCestaVazia"><span class="ttCestaVazia">Sua cesta de compras esta vazia.</span><br/><br/>
								Você ainda não adicionou nenhum produto ao seu carrinho de compras. Navegue pelo site<br/> e selecione os produtos desejados.</p>
								<a href="#"><span class="ButtonCestaVazia" title="continuar comprando">CONTINUAR COMPRANDO</span></a>
							</div>	

					</div>
		</div>
		                <!--Fim da Pagina Vazia do Carrinho de Compras-->		
<?php 
    }
?>	
          <!--Fim da Pagina do Carrinho de Compras-->