<!--**********************RESULTADO DE BUSCA**********************-->
               <div id="cont_central_produtos">

                  <!--SELECT BOX-->
                  	<div id="select_box">
                      <p class="tt_select_box">Ordenar por:</p>
                        <div class="styled-select">
                           <select name="ordenarPor">
                              <option value="">selecione</option>
                              <option value="alfabetica">alfabética</option>
                              <option value="menor_preco">menor preço</option>
                              <option value="maior_preco">maior preço</option>
                           </select>
                        </div>

                        <ul class="box_paginacao">

                            <li class="seta_paginacao">
                              <a href="#">
                                <img class="st_esq" src="<?=$this->basePath()?>/images/seta_esq_paginacao.png">
                              </a>
                            </li>

                          <li><a class="box_numeral_ligado" href="#">1</a></li>
                          <li><a class="box_numeral" href="#">2</a></li>
                          <li><a class="box_numeral" href="#">3</a></li>

                            <li class="seta_paginacao">
                              <a href="#">
                                <img class="st_dir" src="<?=$this->basePath()?>/images/seta_dir_paginacao.png">
                              </a>
                            </li>

                        </ul>
                     </div>
                  <!--FIM DO SELECT BOX-->
                  
                  	<ul id="box_categoria_produtos">
                  	    <!--LISTA DE PRODUTOS-->
                  	    <?php 
                  	    if(isset($this->semresultado)){
                  	    	#echo $this->semresultado;
                  	    	?>
                  	    	<!-- Paulo -->
                  	    	<?php
                  	    }
                  	    else
                        {
                        	
                      	    foreach($this->resultado as $produto)
                      	    {
                      	    	?>
                      	    	<li class="lista_categoria_produtos">
                          			<div id="descricao_produto_categoria">
                          				<a href=""><img class="img_descricao_produto_categoria" src="<?=$this->basePath()?>/images/produto_categoria2.png" title="#"></a>
                          				<p class="txt_descricao_produto_categoria">
                          				    <a class="txt_descricao_produto_categoria" href="<?php echo $this->url('publico-categoria/publico-categoria-e-subcategoria/publico-produto', array('categoriaslug'=>$produto->getProdutosubcategoria()->getCategorias()->getSlug(), 'subcategoriaslugSub'=>$produto->getProdutosubcategoria()->getSlugSubcategoria(), 'produtoSlug'=>$produto->getSlugProduto() )); ?>" title="<?php echo $produto->getTitulo(); ?>">
                          				        <?php echo $produto->getTitulo(); ?>
                          				    </a>
                          				</p>
                          				<strike class="precoAntigo_categoria">R$ 7,50</strike>
        								<p class="precoProduto_categoria">
        								    <em class="moeda_monetaria"><strong><?php echo $produto->getValor(true); ?></strong></em>
        								</p>
                          			</div>
        
                          			<div id="quantidade_produto_categoria" class="prdQtd">
                          				<p class="text_qtd_PC">Quantidade</p>
        								<input id="produto_<?php echo $produto->getIdproduto(); ?>" class="box_qtd_PC" type="text" name="quantidade" value="1">            
        								<ul class="produto_quantidade">
        								    <li class="qtd_mudar_PC qtMais_PC"> <a href="#">mais</a> </li>
                                            <li class="qtd_mudar_PC qtMenos_PC"> <a href="#">menos</a> </li>            									     
        								</ul>
                          			</div>
                          			            
                          			<div id="buttom_add_car_comprar">
        						      <button class="carrinhoCompras_categoria actionAddCarrinho" rev="<?php echo $produto->getIdproduto();?>">Adicionar ao <br/> carrinho de compras</button>            
                          			</div>            
                          		 </li>
                      	    	<?php
                      	    }
                        
                        }
                  	    ?>
                  	    <!--FIM DA LISTA DE PRODUTOS-->                  	    
                  	</ul>


                    <!--SELECT BOX-->
                    <div id="select_box">
                        <p class="tt_select_box">Ordenar por:</p>
                        <div class="styled-select">
                            <select name="ordenarPor">
                                <option value="">selecione</option>
                                <option value="alfabetica">alfabética</option>
                                <option value="menor_preco">menor preço</option>
                                <option value="maior_preco">maior preço</option>
                            </select>
                        </div>

                        <ul class="box_paginacao">                           
                            <li class="seta_paginacao">
                                <a href="#">
                                    <img class="st_esq" src="<?=$this->basePath()?>/images/seta_esq_paginacao.png">
                                </a>
                            </li>
                            <li><a class="box_numeral_ligado" href="#">1</a></li>
                            <li><a class="box_numeral" href="#">2</a></li>
                            <li><a class="box_numeral" href="#">3</a></li>
                            <li class="seta_paginacao">
                                <a href="#">
                                <img class="st_dir" src="<?=$this->basePath()?>/images/seta_dir_paginacao.png">
                                </a>
                            </li>
                        </ul>
                     </div>
                  <!--FIM DO SELECT BOX-->
          </div>
          <!--*********************FIM DOA CATEGORIA***********************-->


<!--*****************MENU LATERAL PUBLICIDADE**********************-->
<div id="publicidade">
    <div id="cadastro">
        <p class="tt_form">Receba ofertas e descontos exclusivos</p>
        <form id="form" method="post" action="">
            <input type="text" class="statusNome" name="nome" placeholder="Digite seu nome" />
            <br class="clear" /> 
            <input type="email" class="statusEmail" name="email" placeholder="Digite seu e-mail" /> 
            <br class="clear" /> 
            <button id="btnEnviar" type="submit" class="cadastrar" title="Enviar">CADASTRAR</button>
        </form>
    </div>

    <div id="face">
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script>
        <div class="fb-like-box" data-href="https://www.facebook.com/SeletoAlimentos?ref=ts&amp;fref=ts" data-width="198" data-height="300" data-show-faces="true" data-header="true" data-stream="false" data-show-border="false"></div>
    </div>
</div>