

                <!--**********************CONTEUDO CENTRAL**********************-->

                  <div id="conteudo_central">

                    <div id="box_destaque">
                      <img class="bt_box"src="../public/images/destaque.png">
                      <p class="txt_box">Produtos em Destaque</p>
                    </div>

                  <ul id="box_produto">
                        <li id="produto" style="border:none">
                          <p class="txt_produto">Café forte torrado e moído - 500g</p>
                          <img src="../public/images/teste.png">
                          <p class="txt_valor">R$ 7,23</p>
                          <a href=""><span class="comprar" title="comprar" alt="comprar">comprar</span></a>
                        </li>

                        <li id="produto">
                          <p class="txt_produto">Café forte torrado e moído - 500g</p>
                          <img src="../public/images/teste.png">
                          <p class="txt_valor">R$ 7,23</p>
                        </li>

                        <li id="produto">
                          <p class="txt_produto">Café forte torrado e moído - 500g</p>
                          <img src="../public/images/teste.png">
                          <p class="txt_valor">R$ 7,23</p>
                        </li>
                  </ul>

                  <div id="box_visitados">
                      <img class="bt_box"src="../public/images/visitados.png">
                      <p class="txt_box">Mais Visitados</p>
                  </div>

                  
                  <ul id="box_produto">

                      <li id="produto" style="border:none">
                        <p class="txt_produto">Café forte torrado e moído - 500g</p>
                        <img src="../public/images/teste.png">
                        <p class="txt_valor">R$ 7,23</p>
                      </li>

                      <li id="produto">
                        <p class="txt_produto">Café forte torrado e moído - 500g</p>
                        <img src="../public/images/teste.png">
                        <p class="txt_valor">R$ 7,23</p>
                      </li>

                      <li id="produto">
                        <p class="txt_produto">Café forte torrado e moído - 500g</p>
                        <img src="../public/images/teste.png">
                        <p class="txt_valor">R$ 7,23</p>
                      </li>

                  </ul>

                </div>

                <!--*********************FIM DO CONTEUDO CENTRAL***********************-->


                <!--*****************MENU LATERAL PUBLICIDADE**********************-->

                  <div id="publicidade">

                    <div id="cadastro">
                      <p class="tt_form">Receba ofertas e descontos exclusivos</p>
                        <form id="form" method="post" action="">
                          <input type="text" class="statusNome" name="nome" placeholder="Digite seu nome" />
                            <br class="clear" /> 
                              <input type="email" class="statusEmail" name="email" placeholder="Digite seu e-mail" /> <br class="clear" /> 
                              <button id="btnEnviar" type="submit" class="cadastrar" title="Enviar">CADASTRAR</button>
                        </form>
                    </div>

                      <div id="face">
                        <div id="fb-root"></div>
                          <script>(function(d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s); js.id = id;
                            js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
                            fjs.parentNode.insertBefore(js, fjs);
                          }(document, 'script', 'facebook-jssdk'));
                          </script>
                          <div class="fb-like-box" data-href="https://www.facebook.com/SeletoAlimentos?ref=ts&amp;fref=ts" data-width="198" data-height="300" data-show-faces="true" data-header="true" data-stream="false" data-show-border="false">
                          </div>
                      </div>
                  </div>
